
name: Run unit test of feature branches 
On: 
push:
branches:
'feature/*'

jobs: 
run-unit-tests

steps:
     - name: Checkout
  uses: actions/checkout@v6.0.2
  - name: run unit test
        run: mvn test
